# Generated by Django 6.0.7 on 2026-07-28 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="The provider's issuer identifier, exactly as it appears in the token.",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The provider's stable identifier for this person.",
                        max_length=255,
                    ),
                ),
                (
                    "subject_source",
                    models.CharField(
                        help_text="Which claim the subject was read from. Recorded so that a configuration change is detectable rather than silently re-linking accounts: Entra's sub is pairwise per application while oid is stable, and swapping between them would otherwise look like a new person.",
                        max_length=64,
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        db_index=True,
                        help_text="Which configured connection this identity last arrived through.",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federated_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "federated identity",
                "verbose_name_plural": "federated identities",
                "indexes": [
                    models.Index(
                        fields=["user", "connection"], name="bastion_fed_user_id_a608ff_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"), name="bastion_identity_unique_issuer_subject"
                    )
                ],
            },
        ),
    ]
