# Generated by Django 6.0.7 on 2026-07-28 11:27

import bastion.audit.events
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bastion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChain",
            fields=[
                ("name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("last_seq", models.BigIntegerField(default=0)),
                ("last_hash", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "audit chain",
            },
        ),
        migrations.CreateModel(
            name="AuditActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pseudonym", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit actor",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("outcome", models.CharField(db_index=True, max_length=16)),
                ("actor_pseudonym", models.CharField(blank=True, db_index=True, max_length=64)),
                ("actor_type", models.CharField(default="user", max_length=16)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("connection", models.CharField(blank=True, db_index=True, max_length=100)),
                ("on_behalf_of", models.CharField(blank=True, max_length=64)),
                ("auth_protocol", models.CharField(blank=True, max_length=32)),
                ("auth_methods", models.JSONField(blank=True, default=list)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=32)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("is_privileged", models.BooleanField(db_index=True, default=False)),
                (
                    "severity",
                    models.CharField(default=bastion.audit.events.Severity["INFO"], max_length=16),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("chain", models.CharField(db_index=True, default="default", max_length=64)),
                ("chain_seq", models.BigIntegerField()),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("record_hash", models.CharField(editable=False, max_length=64)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "audit event",
                "ordering": ("-occurred_at", "-chain_seq"),
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"], name="bastion_aud_event_t_1bf075_idx"
                    ),
                    models.Index(
                        fields=["actor_pseudonym", "occurred_at"],
                        name="bastion_aud_actor_p_f65300_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain", "chain_seq"), name="bastion_audit_chain_seq_unique"
                    )
                ],
            },
        ),
    ]
