# Generated by Django 6.0.7 on 2026-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bastion", "0002_auditchain_auditactor_auditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditchain",
            name="purged_through_seq",
            field=models.BigIntegerField(default=0),
        ),
    ]
