# Generated by Django 6.0.7 on 2026-08-23 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bastion", "0004_breakglassaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeenLogoutToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issuer", models.CharField(max_length=255)),
                ("jti", models.CharField(max_length=255)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="After this the token is refused on age alone, so the row can go.",
                    ),
                ),
                (
                    "seen_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "verbose_name": "seen logout token",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "jti"), name="bastion_logout_token_unique_issuer_jti"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FederatedSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="The Django session this login established.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "sid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The provider's session identifier, where it sends one. Blank is normal: sid is optional, and a provider that omits it can still end every session for a subject, just not one of them.",
                        max_length=255,
                    ),
                ),
                ("connection", models.CharField(db_index=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bastion.federatedidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "federated session",
                "indexes": [
                    models.Index(fields=["identity", "sid"], name="bastion_fed_identit_a7bb84_idx")
                ],
            },
        ),
    ]
